import type { InferInsertModel } from "drizzle-orm";
import type { products, reviews, siteContent } from "./schema";

type ProductSeed = Omit<
  InferInsertModel<typeof products>,
  "id" | "createdAt" | "updatedAt" | "isActive"
>;
type ReviewSeed = Omit<
  InferInsertModel<typeof reviews>,
  "id" | "createdAt" | "isApproved"
>;
type ContentSeed = InferInsertModel<typeof siteContent>;

/**
 * TEMPORARY seed catalog — names/photos reference publicly available web
 * data for development only. Replace with owned product data and imagery
 * before any public launch.
 */
export const productSeeds: ProductSeed[] = [
  {
    slug: "sugar-glaze",
    name: "Sugar Glaze",
    tagline: "Exclusive collection",
    description: "Sugar Glaze is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: "Bestseller",
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_28671a3f-cb0d-425c-a7b8-88194b3ebad8.jpg?v=1768302664&width=1200",
    sortOrder: 0,
  },
  {
    slug: "classic-french",
    name: "Classic French",
    tagline: "Exclusive collection",
    description: "Classic French is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: "Bestseller",
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/NailImages-IcyVeil_4.jpg?v=1771580182&width=1200",
    sortOrder: 1,
  },
  {
    slug: "marshmallow-drip",
    name: "Marshmallow Drip",
    tagline: "Exclusive collection",
    description: "Marshmallow Drip is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: "Bestseller",
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_0cfaf138-2d21-4a26-bfed-7d750bdcca1d.jpg?v=1768312282&width=1200",
    sortOrder: 2,
  },
  {
    slug: "rouge-luxe",
    name: "Rouge Luxe",
    tagline: "Classic single colours",
    description: "Rouge Luxe is a high-gloss lacquered press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    compareAtPrice: 1490,
    finish: "Classic",
    badge: "Bestseller",
    toneA: "#b1453a",
    toneB: "#6e2019",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_d4a48771-4bae-4e17-9f91-5c1ed7f83724.jpg?v=1768311827&width=1200",
    sortOrder: 3,
  },
  {
    slug: "deep-petal",
    name: "Deep Petal",
    tagline: "Exclusive collection",
    description: "Deep Petal is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_531fbed6-bb31-4eff-aef8-926bc93823f2.jpg?v=1768303184&width=1200",
    sortOrder: 4,
  },
  {
    slug: "classic-ombre",
    name: "Classic Ombre",
    tagline: "Exclusive collection",
    description: "Classic Ombre is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_03e672dc-c882-417e-b2c9-3f1e4e03bc96.jpg?v=1768303733&width=1200",
    sortOrder: 5,
  },
  {
    slug: "neutral-flow",
    name: "Neutral Flow",
    tagline: "Exclusive collection",
    description: "Neutral Flow is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_2b051dce-6ac6-4b4f-802c-3fc8f3be7bc2.jpg?v=1768303687&width=1200",
    sortOrder: 6,
  },
  {
    slug: "red-alert",
    name: "Red Alert",
    tagline: "Exclusive collection",
    description: "Red Alert is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#b1453a",
    toneB: "#6e2019",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_8f4593f5-7ecc-4326-88bf-4338d21e9a95.jpg?v=1768311889&width=1200",
    sortOrder: 7,
  },
  {
    slug: "soft-tulle",
    name: "Soft Tulle",
    tagline: "Exclusive collection",
    description: "Soft Tulle is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_693953fc-c917-4318-bd05-29146235481d.jpg?v=1768303865&width=1200",
    sortOrder: 8,
  },
  {
    slug: "dipped-in-gold",
    name: "Dipped In Gold",
    tagline: "Shimmer finish",
    description: "Dipped In Gold is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#eedcae",
    toneB: "#c9a86f",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_0e58785a-89d7-41c1-8b34-a46d41fee5c5.jpg?v=1768308538&width=1200",
    sortOrder: 9,
  },
  {
    slug: "dark-current",
    name: "Dark Current",
    tagline: "Classic single colours",
    description: "Dark Current is a high-gloss lacquered press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Classic",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_79c7ba6a-bd6b-4033-bc03-5a1a4c458e27.jpg?v=1768919550&width=1200",
    sortOrder: 10,
  },
  {
    slug: "dusty-stone",
    name: "Dusty Stone",
    tagline: "Exclusive collection",
    description: "Dusty Stone is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#c9a17e",
    toneB: "#8a6248",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_0e4a635a-ca3c-43db-b7b9-ceb9b7e8356b.jpg?v=1768304395&width=1200",
    sortOrder: 11,
  },
  {
    slug: "mocha-blend",
    name: "Mocha Blend",
    tagline: "Exclusive collection",
    description: "Mocha Blend is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#c9a17e",
    toneB: "#8a6248",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_23a1320e-38d4-4a54-a580-186c2400e08f.jpg?v=1768307565&width=1200",
    sortOrder: 12,
  },
  {
    slug: "pop-crush",
    name: "Pop Crush",
    tagline: "Exclusive collection",
    description: "Pop Crush is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/BeurreDoux.jpg?v=1779190722&width=1200",
    sortOrder: 13,
  },
  {
    slug: "naked-ambition",
    name: "Naked Ambition",
    tagline: "Exclusive collection",
    description: "Naked Ambition is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#e9d7c6",
    toneB: "#c9a98f",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_60739239-9a14-4472-9b5a-a889ddeb7602.jpg?v=1768307951&width=1200",
    sortOrder: 14,
  },
  {
    slug: "dusky-mauve",
    name: "Dusky Mauve",
    tagline: "Exclusive collection",
    description: "Dusky Mauve is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#d8c3d6",
    toneB: "#a98ca4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_9e43e533-39f2-41df-b167-e2a920d044a2.jpg?v=1768304327&width=1200",
    sortOrder: 15,
  },
  {
    slug: "coral-crush",
    name: "Coral Crush",
    tagline: "Exclusive collection",
    description: "Coral Crush is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f0a983",
    toneB: "#d0714c",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/CoralCrush_2.jpg?v=1779189440&width=1200",
    sortOrder: 16,
  },
  {
    slug: "milkyway",
    name: "Milkyway",
    tagline: "Shimmer finish",
    description: "Milkyway is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_52b07c79-a536-401a-bd88-f8ab62c6ebfd.jpg?v=1768308320&width=1200",
    sortOrder: 17,
  },
  {
    slug: "dusty-blush",
    name: "Dusty Blush",
    tagline: "Exclusive collection",
    description: "Dusty Blush is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_48803a2e-abd5-4db2-aa2b-3674bee3bad9.jpg?v=1768312152&width=1200",
    sortOrder: 18,
  },
  {
    slug: "berry-confident",
    name: "Berry Confident",
    tagline: "Exclusive collection",
    description: "Berry Confident is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/BerryConfident.jpg?v=1779189756&width=1200",
    sortOrder: 19,
  },
  {
    slug: "pastel-haze",
    name: "Pastel Haze",
    tagline: "Shimmer finish",
    description: "Pastel Haze is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_26e38d94-2fd1-4d55-b795-58faa8f07ea3.jpg?v=1768304605&width=1200",
    sortOrder: 20,
  },
  {
    slug: "rosewater-silk",
    name: "Rosewater Silk",
    tagline: "Exclusive collection",
    description: "Rosewater Silk is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_1cdeaebe-d5a7-4a32-bb2c-28914dac6c1e.jpg?v=1768311934&width=1200",
    sortOrder: 21,
  },
  {
    slug: "perle-de-paris",
    name: "Perle de Paris",
    tagline: "Exclusive collection",
    description: "Perle de Paris is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_03ce2c35-c751-42f1-aabf-d744542919ec.jpg?v=1779190218&width=1200",
    sortOrder: 22,
  },
  {
    slug: "coconut-milk",
    name: "Coconut Milk",
    tagline: "Exclusive collection",
    description: "Coconut Milk is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_16884c43-5bbc-4dc5-9d8e-e6ef904f3175.jpg?v=1768311595&width=1200",
    sortOrder: 23,
  },
  {
    slug: "golden-hour",
    name: "Golden Hour",
    tagline: "Shimmer finish",
    description: "Golden Hour is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#eedcae",
    toneB: "#c9a86f",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_c172fc27-c40d-4e74-b02f-c54161c909db.jpg?v=1768307516&width=1200",
    sortOrder: 24,
  },
  {
    slug: "silk-finish",
    name: "Silk Finish",
    tagline: "Exclusive collection",
    description: "Silk Finish is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_5fa886cc-b4fd-4c9a-b2d5-d331c4b1544c.jpg?v=1768303819&width=1200",
    sortOrder: 25,
  },
  {
    slug: "bare-mulberry",
    name: "Bare Mulberry",
    tagline: "Exclusive collection",
    description: "Bare Mulberry is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#d8c3d6",
    toneB: "#a98ca4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_69ef18bf-fc55-4d59-8911-cdada9d3900a.jpg?v=1768307723&width=1200",
    sortOrder: 26,
  },
  {
    slug: "blue-eclipse",
    name: "Blue Eclipse",
    tagline: "Classic single colours",
    description: "Blue Eclipse is a high-gloss lacquered press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Classic",
    badge: null,
    toneA: "#3a4a6b",
    toneB: "#141d31",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_9d643d0c-8d7b-41c3-a232-8e6ca6e7bfbd.jpg?v=1768303129&width=1200",
    sortOrder: 27,
  },
  {
    slug: "sparkling-ember",
    name: "Sparkling Ember",
    tagline: "Shimmer finish",
    description: "Sparkling Ember is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_a6ff78db-40f8-480d-b832-2228a3052948.jpg?v=1768302822&width=1200",
    sortOrder: 28,
  },
  {
    slug: "liquorice",
    name: "Liquorice",
    tagline: "Classic single colours",
    description: "Liquorice is a high-gloss lacquered press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Classic",
    badge: null,
    toneA: "#3a3430",
    toneB: "#0e0b0a",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_ea1495fc-0060-49c4-9623-585c5e750c5d.jpg?v=1768311540&width=1200",
    sortOrder: 29,
  },
  {
    slug: "peach-perfect",
    name: "Peach Perfect",
    tagline: "Exclusive collection",
    description: "Peach Perfect is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f0a983",
    toneB: "#d0714c",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/PeachPerfect.jpg?v=1779189698&width=1200",
    sortOrder: 30,
  },
  {
    slug: "saintly-sweet",
    name: "Saintly Sweet",
    tagline: "Exclusive collection",
    description: "Saintly Sweet is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/BeurreSoleil_3.jpg?v=1772541058&width=1200",
    sortOrder: 31,
  },
  {
    slug: "rose-tone",
    name: "Rose Tone",
    tagline: "Exclusive collection",
    description: "Rose Tone is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_f3fce684-2d2a-4923-ae2c-67e1da3d6be3.jpg?v=1768303259&width=1200",
    sortOrder: 32,
  },
  {
    slug: "rose-spark",
    name: "Rose Spark",
    tagline: "Shimmer finish",
    description: "Rose Spark is a light-catching shimmer press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    finish: "Signature",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_0ac3f1be-71d8-4701-943a-90623befb121.jpg?v=1768302949&width=1200",
    sortOrder: 33,
  },
  {
    slug: "cherry-smoke",
    name: "Cherry Smoke",
    tagline: "Exclusive collection",
    description: "Cherry Smoke is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#8a3540",
    toneB: "#4e1a20",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_e7fc97d2-ad82-42d8-84c8-20516fd3229a.jpg?v=1768304730&width=1200",
    sortOrder: 34,
  },
  {
    slug: "lavender-blush",
    name: "Lavender Blush",
    tagline: "Exclusive collection",
    description: "Lavender Blush is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#d8c3d6",
    toneB: "#a98ca4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_2577b640-bec8-4120-a9f4-0fb64810d0a5.jpg?v=1768307816&width=1200",
    sortOrder: 35,
  },
  {
    slug: "ocean-dream",
    name: "Ocean Dream",
    tagline: "Exclusive collection",
    description: "Ocean Dream is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#a9c4d4",
    toneB: "#5e7f96",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_acb5bf92-e577-48f4-b3fe-06f9d090a867.jpg?v=1768308272&width=1200",
    sortOrder: 36,
  },
  {
    slug: "blush-glaze",
    name: "Blush Glaze",
    tagline: "Exclusive collection",
    description: "Blush Glaze is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/BlushGlaze1.jpg?v=1779354022&width=1200",
    sortOrder: 37,
  },
  {
    slug: "doll-moment",
    name: "Doll Moment",
    tagline: "Exclusive collection",
    description: "Doll Moment is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_783c924c-79e3-4ff6-a122-0e89167801bd.jpg?v=1768307428&width=1200",
    sortOrder: 38,
  },
  {
    slug: "hotline-edit",
    name: "Hotline Edit",
    tagline: "Classic single colours",
    description: "Hotline Edit is a high-gloss lacquered press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1250,
    compareAtPrice: 1490,
    finish: "Classic",
    badge: null,
    toneA: "#b1453a",
    toneB: "#6e2019",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_584c7669-ca1f-4f5b-993a-ec9220f101dc.jpg?v=1768303977&width=1200",
    sortOrder: 39,
  },
  {
    slug: "cloud-nine",
    name: "Cloud Nine",
    tagline: "Exclusive collection",
    description: "Cloud Nine is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/CloudNine.jpg?v=1779189845&width=1200",
    sortOrder: 40,
  },
  {
    slug: "coral-kiss",
    name: "Coral Kiss",
    tagline: "Exclusive collection",
    description: "Coral Kiss is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f0a983",
    toneB: "#d0714c",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_caf39305-e554-4dbb-ba59-918289d56750.jpg?v=1768304168&width=1200",
    sortOrder: 41,
  },
  {
    slug: "blooming-days",
    name: "Blooming Days",
    tagline: "Exclusive collection",
    description: "Blooming Days is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/BloomingDays_406f5049-4855-401b-a516-af9de44eb659.jpg?v=1779189932&width=1200",
    sortOrder: 42,
  },
  {
    slug: "pink-whisper",
    name: "Pink Whisper",
    tagline: "Exclusive collection",
    description: "Pink Whisper is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/PinkWhisper.jpg?v=1779189633&width=1200",
    sortOrder: 43,
  },
  {
    slug: "powder-puff",
    name: "Powder Puff",
    tagline: "Exclusive collection",
    description: "Powder Puff is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f4ece2",
    toneB: "#d8c7b4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/Powder_Puff_1_adb1104a-a526-479c-8a7b-f93f305fc0c5.png?v=1774257025&width=1200",
    sortOrder: 44,
  },
  {
    slug: "wild-french",
    name: "Wild French",
    tagline: "Exclusive collection",
    description: "Wild French is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#f2d5d0",
    toneB: "#dfa9a2",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_8c336eab-ed11-4b4b-84d9-42f11fed3ca7.jpg?v=1768307039&width=1200",
    sortOrder: 45,
  },
  {
    slug: "lilac-smoke",
    name: "Lilac Smoke",
    tagline: "Exclusive collection",
    description: "Lilac Smoke is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#d8c3d6",
    toneB: "#a98ca4",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_6b26862f-82f8-45f6-82ec-348d9bbdfb1f.jpg?v=1768303013&width=1200",
    sortOrder: 46,
  },
  {
    slug: "bare-minimum",
    name: "Bare Minimum",
    tagline: "Exclusive collection",
    description: "Bare Minimum is a smooth, cream-finish press-on set — salon-sculpted, hand-finished, and ready in ten minutes.",
    price: 1150,
    finish: "Exclusive",
    badge: null,
    toneA: "#e9d7c6",
    toneB: "#c9a98f",
    imageUrl: "https://cdn.shopify.com/s/files/1/0396/9279/6066/files/1_43f6cdbf-41ca-4d9d-8314-6bcd9ce00f07.jpg?v=1768307244&width=1200",
    sortOrder: 47,
  },
  {
    slug: "protouch-kit-max",
    name: "ProTouch Kit Max",
    tagline: "Tools & Accessories",
    description: "Complete studio UV & solid gel glue system. Includes rechargeable UV LED flash curing lamp, solid nail glue gel max tube, and dual precision application tools for a flawless, bubble-free 4-week manicure.",
    price: 1650,
    compareAtPrice: 2300,
    finish: "Classic",
    badge: "Bestseller",
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/protouch-kit-max.png",
    sizes: ["tool"],
    sortOrder: 48,
  },
  {
    slug: "protouch-kit",
    name: "ProTouch Kit",
    tagline: "Tools & Accessories",
    description: "Compact UV LED flash cure light, 2 solid glue gel pots, and a dual-ended cuticle prep pen for effortless press-on application.",
    price: 1400,
    compareAtPrice: 2000,
    finish: "Classic",
    badge: "Bestseller",
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/protouch-kit.png",
    sizes: ["tool"],
    sortOrder: 49,
  },
  {
    slug: "semi-solid-glue-kit",
    name: "Semi Solid Nail Glue Kit",
    tagline: "Tools & Accessories",
    description: "High-viscosity tube glue formula that holds firm without running into cuticles. Paired with our gentle citrus-infused solvent for fast, damage-free removal.",
    price: 850,
    compareAtPrice: 1150,
    finish: "Classic",
    badge: null,
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/semi-solid-glue-kit.png",
    sizes: ["tool"],
    sortOrder: 50,
  },
  {
    slug: "magic-glue-kit",
    name: "Magic Brush-On Glue Kit",
    tagline: "Tools & Accessories",
    description: "Salon-strength brush applicator gives micro-thin, even coverage across your natural nail plate. Instant 10-second bond with no UV light required.",
    price: 850,
    compareAtPrice: 1100,
    finish: "Classic",
    badge: "Bestseller",
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/magic-glue-kit.jpg",
    sizes: ["tool"],
    sortOrder: 51,
  },
  {
    slug: "sticky-tabs-pack",
    name: "3M Ultra-Hold Adhesive Tabs (Pack of 5)",
    tagline: "Tools & Accessories",
    description: "Medical-grade 3M adhesive tabs engineered specifically for reusable press-on nails. Zero damage to natural nail keratin, waterproof seal, and instant peel-off removal.",
    price: 350,
    compareAtPrice: 450,
    finish: "Classic",
    badge: null,
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/sticky-tabs.jpg",
    sizes: ["tool"],
    sortOrder: 52,
  },
  {
    slug: "precision-removal-pen",
    name: "Precision Gel Removal Pen",
    tagline: "Tools & Accessories",
    description: "Twist-click precision applicator pen saturated with nourishing oils and gentle adhesive-releasing agents. Dissolves glue bonds seamlessly at the cuticle perimeter in 2 minutes.",
    price: 500,
    compareAtPrice: 650,
    finish: "Classic",
    badge: null,
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/removal-pen.png",
    sizes: ["tool"],
    sortOrder: 53,
  },
  {
    slug: "solid-glue-gel-max",
    name: "Solid Nail Glue Gel Max (Tube)",
    tagline: "Tools & Accessories",
    description: "Sculptable solid gel texture that lets you position and reposition your press-ons before curing under UV light. Zero air bubbles, non-sticky to fingertips, and up to 4 weeks duration.",
    price: 650,
    compareAtPrice: 900,
    finish: "Classic",
    badge: null,
    toneA: "#faf7f5",
    toneB: "#e8ded8",
    imageUrl: "/tools/solid-glue-gel.png",
    sizes: ["tool"],
    sortOrder: 54,
  },
];

export const reviewSeeds: ReviewSeed[] = [
  {
    productId: null,
    authorName: "Anika R.",
    location: "Dhaka",
    rating: 5,
    body: "I wore Rouge Luxe through a full wedding season — three events, endless errands, zero chips. My salon has officially lost me.",
  },
  {
    productId: null,
    authorName: "Tashfia H.",
    location: "Chattogram",
    rating: 5,
    body: "The finish looks like a ৳3,000 gel manicure. Nobody believes they press on in ten minutes. Neither did I.",
  },
  {
    productId: null,
    authorName: "Mahruf K.",
    location: "Sylhet",
    rating: 5,
    body: "My natural nails have finally grown back. Removal takes five minutes and leaves nothing behind. This is the way.",
  },
];

export const contentSeeds: ContentSeed[] = [
  {
    key: "announcements",
    value: [
      "Free Delivered anywhere in Bangladesh", 
      "New shades just landed",
    ],
  },
  {
    key: "marquee",
    value: [
      "Hand-finished in Dhaka",
      "Damage-free removal",
      "Reusable up to 5 wears",
      "Cruelty-free formula",
      "Delivered nationwide",
      "10-minute application",
    ],
  },
];
